# Generated by Django 2.0.6 on 2018-06-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=3)),
                ('state', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=50)),
                ('auto_break', models.BooleanField(default=0)),
                ('dailyOvertimeMultiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dailyOvertimeThreshold', models.SmallIntegerField()),
                ('overtime', models.BooleanField()),
                ('weeklyOvertimeMultiplier', models.SmallIntegerField()),
                ('weeklyOvertimeThreshold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.Company')),
            ],
        ),
        migrations.CreateModel(
            name='LocationLabourSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_length', models.SmallIntegerField()),
                ('threshold', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.Location')),
            ],
        ),
    ]
